import type { Metadata } from "next";
import { Inter  } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { Toaster } from "react-hot-toast";

const inter  = Inter ({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter ",
});

export const metadata: Metadata = {
  title: "RoboFx",
  description: "Generated by roboFx",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter .variable} light`}>
      <body>
          <Providers>{children}</Providers>
          <Toaster />
      </body>
    </html>
  );
}
